"""
models.py
---------
Data models and enumerations for the Doubt Resolution System.

This file defines the "blueprints" for data that travels between all other
modules. Nothing in here does any real work — it just describes what a
Question looks like and what status values are valid.

Other files import from here so every part of the project uses the same
consistent data structure.
"""

# Enum  — a special class that defines a fixed set of named constants.
# Using an Enum instead of plain strings like "Pending" prevents typos
# (e.g., typing "pendng" by accident would never match).
from enum import Enum

# dataclass — a decorator that automatically generates __init__, __repr__,
# and other boilerplate methods for a class that just holds data fields.
from dataclasses import dataclass, field

from datetime import datetime


# ---------------------------------------------------------------------------
# Question lifecycle states
# A question moves through these states in order:
#   Pending → AI Answer Generated → Instructor Verified
# ---------------------------------------------------------------------------
class QuestionStatus(Enum):
    PENDING = "Pending"                       # Just submitted, no answer yet
    AI_ANSWERED = "AI Answer Generated"       # AI has generated an answer
    INSTRUCTOR_VERIFIED = "Instructor Verified"  # A human instructor has reviewed it


# ---------------------------------------------------------------------------
# The full list of subjects a student can assign to their question.
# This list is used in both the GUI dropdown and the CLI numbered menu.
# ---------------------------------------------------------------------------
SUPPORTED_SUBJECTS = [
    "Computer Science",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Politics",
    "History",
    "Economics",
    "Philosophy",
    "General Knowledge",
]


# ---------------------------------------------------------------------------
# Question — the main data object.
# Every question in the system is represented as one of these objects.
# The @dataclass decorator means Python auto-generates the __init__ method,
# so you can create a Question like: Question(question_id=1, student_name="Ali", ...)
# ---------------------------------------------------------------------------
@dataclass
class Question:
    question_id: int          # Unique number automatically assigned by the database
    student_name: str         # Name the student entered when posting
    subject: str              # Subject chosen from SUPPORTED_SUBJECTS
    question_text: str        # The actual question typed by the student

    # Fields below have default values — they start empty and get filled in later
    status: str = QuestionStatus.PENDING.value       # Current state (see QuestionStatus)
    ai_answer: str = ""                               # Answer generated by the AI engine
    instructor_answer: str = ""                       # Answer provided by a human instructor
    ai_confidence: float = 0.0                        # How confident the AI is (0.0 – 1.0)
    keywords: str = ""                                # Comma-separated key terms extracted from the question
    topic: str = ""                                   # Sub-topic detected (e.g., "Calculus", "Machine Learning")

    # Default timestamp: the current date/time when the object is created
    timestamp: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
